HOMEBREWFIX_GIT = https://github.com/tolsadus/42homebrewfix.git

BREW_INSTALLER = $(BREW_INSTALLER_PATH)/install.sh

BREW_INSTALLER_DIR = brew_installer

BREW_INSTALLER_PATH = $(PROJECT_PATH)/$(BREW_INSTALLER_DIR)

BREW = $(BREW_BIN_PATH)/brew

BREW_DIR = .brew

BREW_PATH = ~/$(BREW_DIR)

BREW_BIN_DIR = bin

BREW_BIN_PATH = $(BREW_PATH)/$(BREW_BIN_DIR)

BREW_SBIN_DIR = sbin

BREW_SBIN_PATH = $(BREW_PATH)/$(BREW_SBIN_DIR)

BREW_LIB_DIR = lib

BREW_LIB_PATH = $(BREW_PATH)/$(BREW_LIB_DIR)

BREW_ETC_DIR = etc

BREW_ETC_PATH = $(BREW_PATH)/$(BREW_ETC_DIR)

BREW_OPT_DIR = opt

BREW_OPT_PATH = $(BREW_PATH)/$(BREW_OPT_DIR)

BREW_SHARE_DIR = share

BREW_SHARE_PATH = $(BREW_PATH)/$(BREW_SHARE_DIR)

BREW_DOCS_DIR = docs

BREW_DOCS_PATH = $(BREW_PATH)/$(BREW_DOCS_DIR)

BREW_INCLUDE_DIR = include

BREW_INCLUDE_PATH = $(BREW_PATH)/$(BREW_INCLUDE_DIR)

BREW_MAN_DIR = manpages

BREW_MAN_PATH = $(BREW_PATH)/$(BREW_MAN_DIR)

BREW_VAR_DIR = var

BREW_VAR_PATH = $(BREW_PATH)/$(BREW_VAR_DIR)

BREW_UNINSTALLER_URL = \
	https://raw.githubusercontent.com/Homebrew/install/master/uninstall

BREW_UNINSTALLER_RUBY_COMMAND = "$(curl -fsSL $(BREW_UNINSTALLER_URL))"

HG = $(BREW_BIN_PATH)/hg

RUBY = $(BREW_BIN_PATH)/ruby