LIBFT_PATH := $(shell pwd)/libft

LIBFT_MK_DIR := mk

LIBFT_MK_PATH := $(LIBFT_PATH)/$(LIBFT_MK_DIR)

INCLUDE_DIR ?= include

INCLUDE_PATH += $(LIBFT_PATH)/$(INCLUDE_DIR)

LINK_PATH += $(LIBFT_PATH)

MAKE_LIBFT = @$(MAKE) -C $(LIBFT_PATH) $@