SDL_SRC_DIR = SRC

SDL_SRC_PATH = $(SDL_BUILD_PATH)/$(SDL_SRC_DIR)

SDL_BUILD_DIR = SDL

SDL_BUILD_PATH = $(PROJECT_PATH)/$(SDL_BUILD_DIR)

SDL_BUILD_MAKEFILE = $(SDL_BUILD_PATH)/Makefile

SDL_PREBUILD_PATH = $(SDL_BUILD_PATH)/build

SDL_INCLUDE_DIR = include

SDL_INCLUDE_PATH = $(SDL_BUILD_PATH)/$(SDL_INCLUDE_DIR)

SDL_LIB_DIR = lib

SDL_LIB_PATH = $(SDL_BUILD_PATH)/$(SDL_LIB_DIR)

MAKE_SDL = $(SDL_LIB_PATH)/libSDL2.a

SDL_SRC_AUTOGEN = cd $(SDL_SRC_PATH) && sh autogen.sh

SDL_BUILD_CONFIGURE = cd $(SDL_BUILD_PATH) && \
	$(SDL_SRC_PATH)/configure $(SDL_BUILD_CONFIGURE_FLAGS)

SDL_DATAROOTDIR = $(SDL_BUILD_PATH)/data

SDL_DOCROOTDIR = $(SDL_DATAROOTDIR)/doc

SDL_BUILD_CONFIGURE_FLAGS = \
	--prefix=$(SDL_BUILD_PATH) --exec-prefix=$(SDL_BUILD_PATH) \
	--datadir=$(SDL_DATAROOTDIR) --docdir=$(SDL_DOCROOTDIR) \
	--oldincludedir=$(SDL_INCLUDE_PATH)

RMDIR_SDL = $(RMDIR) $(SDL_BUILD_PATH)

LIBSDL_HG = https://hg.libsdl.org/SDL
