SDL_LIB_NAME = libSDL2.a

LIBSDL_SUFFIX = SDL2

SDL_INCLUDE_PATH = $(BREW_INCLUDE_PATH)/$(LIBSDL_SUFFIX)

SDL_LIBRARY_PATH = LIBRARY_PATH=$(BREW_LIB_PATH):$$LIBRARY_PATH

SDL_LD_LIBRARY_PATH = LD_LIBRARY_PATH=$(BREW_LIB_PATH):$$LD_LIBRARY_PATH

SDL_INCLUDE = INCLUDE=$(BREW_INCLUDE_PATH):$(SDL_INCLUDE_PATH):$$INCLUDE

SDL_CPATH = CPATH=$(BREW_INCLUDE_PATH):$(SDL_INCLUDE_PATH):$$CPATH

MAKE_SDL = $(BREW_LIB_PATH)/$(SDL_LIB_NAME)

BREW_FIX_ZSH = $(HOME)/.brew_fix.zsh

BREW_FIX_ZSH_BACKUP = $(HOME)/.brew_fix.zsh.backup

define SDL_FIX

# Add paths to librarys and includes
export $(SDL_LIBRARY_PATH)
export $(SDL_LD_LIBRARY_PATH)
export $(SDL_INCLUDE)
export $(SDL_CPATH)
endef

export SDL_FIX